import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useCart } from '../../application/contexts/CartContext';
import { PhoneInput } from 'react-international-phone';
import 'react-international-phone/style.css';
import './CheckoutPage.css';

// Environment variables
const WHATSAPP_NUMBER = import.meta.env.VITE_WHATSAPP_NUMBER || '5511999999999';

/**
 * Checkout Page
 * Handles order finalization with WhatsApp or PIX payment options
 */
export function CheckoutPage() {
  const { cart, updateQuantity, removeFromCart, getTotal } = useCart();
  const navigate = useNavigate();
  const [paymentMethod, setPaymentMethod] = useState(null); // 'whatsapp' or 'pix'
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [showPixForm, setShowPixForm] = useState(false);
  const [pixQrCode, setPixQrCode] = useState(null);

  const handleQuantityChange = (productId, newQuantity) => {
    if (newQuantity >= 1) {
      updateQuantity(productId, newQuantity);
    }
  };

  const handleRemove = (productId) => {
    removeFromCart(productId);
  };

  const generateWhatsAppMessage = (includeContactInfo = false) => {
    let message = '*Pedido VZ Dolci*%0A%0A';
    
    cart.forEach(item => {
      message += `${item.product.name} x${item.quantity} - R$ ${item.getTotal().toFixed(2)}%0A`;
    });
    
    const total = getTotal();
    message += `%0A*Total: R$ ${total.toFixed(2)}*`;

    if (includeContactInfo && (email || phone)) {
      message += `%0A%0A*Forma de Pagamento:* PIX`;
      if (email) {
        message += `%0A*Email:* ${email}`;
      }
      if (phone) {
        message += `%0A*Telefone:* ${phone}`;
      }
    }
    
    return message;
  };

  const handleWhatsAppCheckout = () => {
    if (cart.length === 0) {
      alert('Seu carrinho está vazio!');
      return;
    }

    const message = generateWhatsAppMessage(false);
    const whatsappLink = `https://wa.me/${WHATSAPP_NUMBER}?text=${message}`;
    window.open(whatsappLink, '_blank');
  };

  const handlePixCheckout = () => {
    if (cart.length === 0) {
      alert('Seu carrinho está vazio!');
      return;
    }

    setPaymentMethod('pix');
    setShowPixForm(true);
  };

  const handlePixPaymentConfirm = () => {
    // Validate that at least one contact method is provided
    if (!email.trim() && !phone) {
      alert('Por favor, informe pelo menos um método de contato (email ou telefone)!');
      return;
    }

    // Email validation if provided
    if (email.trim()) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email)) {
        alert('Por favor, informe um email válido!');
        return;
      }
    }

    // Phone validation if provided
    if (phone && phone.length < 10) {
      alert('Por favor, informe um telefone válido!');
      return;
    }

    // Generate a simple PIX QR Code (in a real scenario, this would be generated by a backend)
    const pixCode = `00020126580014BR.GOV.BCB.PIX0136${Date.now()}520400005303986540${getTotal().toFixed(2)}5802BR5913VZ Dolci6009SAO PAULO62070503***6304`;
    setPixQrCode(pixCode);

    // Send WhatsApp message in the background (user doesn't see this)
    const message = generateWhatsAppMessage(true);
    const whatsappLink = `https://wa.me/${WHATSAPP_NUMBER}?text=${message}`;
    
    // Open in a hidden/background way (we'll use a timeout and then close it)
    const hiddenWindow = window.open(whatsappLink, '_blank');
    setTimeout(() => {
      if (hiddenWindow) {
        hiddenWindow.close();
      }
    }, 1000);
  };

  if (cart.length === 0) {
    return (
      <main>
        <section className="section checkout-section">
          <div className="container">
            <h2 className="section-title">Finalizar Compra</h2>
            <div className="empty-checkout">
              <span className="empty-icon">🛒</span>
              <p>Seu carrinho está vazio!</p>
              <button className="btn btn-primary" onClick={() => navigate('/produtos')}>
                Ver Produtos
              </button>
            </div>
          </div>
        </section>
      </main>
    );
  }

  return (
    <main>
      <section className="section checkout-section">
        <div className="container">
          <h2 className="section-title">Finalizar Compra</h2>
          <p className="section-subtitle">Revise seu pedido e escolha a forma de pagamento</p>

          <div className="checkout-container">
            {/* Cart Items */}
            <div className="checkout-items">
              <h3>Itens do Pedido</h3>
              {cart.map((item) => (
                <div key={item.product.id} className="checkout-item">
                  <div className="checkout-item-info">
                    <span className="checkout-item-emoji">{item.product.emoji}</span>
                    <div className="checkout-item-details">
                      <h4>{item.product.name}</h4>
                      <p className="checkout-item-description">{item.product.description}</p>
                      <p className="checkout-item-price">R$ {item.product.price.toFixed(2)} (unidade)</p>
                    </div>
                  </div>
                  
                  <div className="checkout-item-actions">
                    <div className="quantity-controls">
                      <button 
                        className="qty-btn"
                        onClick={() => handleQuantityChange(item.product.id, item.quantity - 1)}
                        disabled={item.quantity <= 1}
                        aria-label="Diminuir quantidade"
                      >
                        -
                      </button>
                      <span className="quantity">{item.quantity}</span>
                      <button 
                        className="qty-btn"
                        onClick={() => handleQuantityChange(item.product.id, item.quantity + 1)}
                        aria-label="Aumentar quantidade"
                      >
                        +
                      </button>
                    </div>
                    <button 
                      className="remove-btn"
                      onClick={() => handleRemove(item.product.id)}
                      title="Remover item"
                      aria-label="Remover item"
                    >
                      🗑️
                    </button>
                  </div>
                  
                  <div className="checkout-item-total">
                    Subtotal: R$ {item.getTotal().toFixed(2)}
                  </div>
                </div>
              ))}

              <div className="checkout-total">
                <strong>Total do Pedido:</strong>
                <strong className="total-amount">R$ {getTotal().toFixed(2)}</strong>
              </div>
            </div>

            {/* Payment Options */}
            <div className="checkout-payment">
              <h3>Forma de Pagamento</h3>
              
              {!showPixForm ? (
                <div className="payment-options">
                  <button 
                    className="payment-option whatsapp-option"
                    onClick={handleWhatsAppCheckout}
                  >
                    <span className="payment-icon">💬</span>
                    <div className="payment-option-content">
                      <h4>WhatsApp</h4>
                      <p>Finalize seu pedido enviando uma mensagem</p>
                    </div>
                  </button>

                  <button 
                    className="payment-option pix-option"
                    onClick={handlePixCheckout}
                  >
                    <span className="payment-icon">💳</span>
                    <div className="payment-option-content">
                      <h4>PIX</h4>
                      <p>Pague agora com PIX e receba confirmação</p>
                    </div>
                  </button>
                </div>
              ) : (
                <div className="pix-payment-section">
                  {!pixQrCode ? (
                    <form className="pix-form" onSubmit={(e) => {
                      e.preventDefault();
                      handlePixPaymentConfirm();
                    }}>
                      <h4>Informações de Contato</h4>
                      <p>Informe pelo menos um método de contato (email ou telefone):</p>
                      <input
                        type="email"
                        className="contact-input"
                        placeholder="Email (exemplo@dominio.com)"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                        autoComplete="email"
                      />
                      <PhoneInput
                        defaultCountry="br"
                        className="phone-input-container"
                        placeholder="Telefone"
                        value={phone}
                        onChange={(phone) => setPhone(phone)}
                      />
                      <div className="pix-form-actions">
                        <button 
                          type="button"
                          className="btn btn-secondary"
                          onClick={() => {
                            setShowPixForm(false);
                            setPaymentMethod(null);
                            setEmail('');
                            setPhone('');
                          }}
                        >
                          Voltar
                        </button>
                        <button 
                          type="submit"
                          className="btn btn-primary"
                        >
                          Gerar QR Code PIX
                        </button>
                      </div>
                    </form>
                  ) : (
                    <div className="pix-qrcode-section">
                      <h4>QR Code PIX</h4>
                      <div className="qrcode-placeholder">
                        <div className="qrcode-box">
                          {/* Simple visual representation - in production, use a library like qrcode.react */}
                          <div className="qrcode-pattern">
                            <div></div><div></div><div></div>
                            <div></div><div></div><div></div>
                            <div></div><div></div><div></div>
                          </div>
                          <p className="qrcode-label">QR CODE PIX</p>
                        </div>
                      </div>
                      <div className="pix-code-copy">
                        <p>Código PIX:</p>
                        <div className="code-box">
                          <code>{pixQrCode.substring(0, 50)}...</code>
                          <button 
                            className="copy-btn"
                            onClick={() => {
                              navigator.clipboard.writeText(pixQrCode);
                              alert('Código PIX copiado!');
                            }}
                          >
                            📋 Copiar
                          </button>
                        </div>
                      </div>
                      <div className="pix-instructions">
                        <p><strong>Instruções:</strong></p>
                        <ol>
                          <li>Abra o app do seu banco</li>
                          <li>Escolha pagar com PIX</li>
                          <li>Escaneie o QR Code ou cole o código PIX</li>
                          <li>Confirme o pagamento de R$ {getTotal().toFixed(2)}</li>
                        </ol>
                        <p className="contact-confirmation">
                          ✅ Você receberá confirmação quando seu pedido estiver pronto!
                          <br /><strong>Email:</strong> {email}
                          <br /><strong>Telefone:</strong> {phone}
                        </p>
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        </div>
      </section>
    </main>
  );
}
